---
- hosts: dev
  tasks:
    - name: install apache2
      action: apt name=apache2 state=present
      when: ansible_os_family == "Debian"
    - name: install httpd
      action: yum name=httpd state=present
      when: ansible_os_family == "RedHat"