---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
      git_repo_url: https://example.org/path/to/hello-world.git
      repo_path: /your/local/repo/path
      repo_branch: master
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - wget
      - nginx
      - nodejs
  - name: Clone a private repository
    git:
     repo: "{{ git_repo_url }}"
     dest: "{{ repo_path }}"
     version: "{{ repo_branch }}"
     accept_hostkey: yes
  - name: Install packages based on package.json using the npm
    npm:
      path: "{{ repo_path }}"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "{{ repo_path }}"