---
- name: Example Ansible playbook
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      notify: Start Apache

    # other regular tasks…

  handlers:          # handlers
    - name: Start Apache
      shell: /usr/sbin/apache2ctl start
      args:
        creates: /var/run/apache2/apache2.pid

    - name: Reload Apache
      shell: /usr/sbin/apache2ctl -k graceful
      args:
        creates: /var/run/apache2/apache2.pid
